// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { ThemeProvider } from "next-themes";
import Footer from "@/components/Footer";
import Script from "next/script"; // ✅ Import Script
import { AuthProvider } from "@/context/AuthContext";
import { TnCAlertDialog } from "@/components/AlertDialogue";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Cloudflare Web Analytics Script */}
        <Script
          defer
          src="https://static.cloudflareinsights.com/beacon.min.js"
          data-cf-beacon='{"token": "ec707fbbd78c41ff8b1d2c32ae5c75e2"}'
          strategy="afterInteractive"
        />
      </head>
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <nav className="fixed top-0 left-0 right-0 z-50">
              <Navbar />
            </nav>
            <main className="mt-21">
              <AuthProvider>
                <TnCAlertDialog />
                {children}</AuthProvider>
            </main>
            <Footer />
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
